version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  deps-install:
    docker:
      - image:  circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-node12-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - yarn-install-node12-{{ checksum "package.json" }}
            - yarn-install-node12
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-node12-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  code-lint:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  commit-lint:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint:commit:ci

  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn test:coverage
      - codecov/upload:
          file: coverage/*.json

  publish:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - deps-install
      - code-lint:
          requires:
            - deps-install
      - commit-lint:
          requires:
            - deps-install
      - test:
          requires:
            - deps-install
      - publish:
          context: semver
          filters:
            branches:
              only:
                - master
          requires:
            - code-lint
            - commit-lint
